<?php

namespace Database\Seeders;

use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use App\Models\Admin;
use App\Models\Kriteria;
use App\Models\Penilaian;
use App\Models\SubKriteria;
use App\Models\TipeKriteria;
use App\Models\CalonPenerima;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {

        User::factory()->create([
            'name' => 'user',
            'email' => 'user@gmail.com',
            'password' => Hash::make('user'),
        ]);

        Admin::factory()->create([
            'name' => 'admin',
            'email' => 'admin@gmail.com',
            'password' => Hash::make('admin'),
        ]);

        $dataKriteria = [
            [
                'kode' => 'C1',
                'nama_kriteria' => 'Pekerjaan Suami',
                'tipe' => TipeKriteria::Cost,

                'sub_kriteria' => [
                    ['label' => 'PNS', 'bobot' => 1],
                    ['label' => 'Wirausaha/Wiraswasta', 'bobot' => 2],
                    ['label' => 'Petani', 'bobot' => 3],
                    ['label' => 'Buruh', 'bobot' => 4],
                    ['label' => 'Pengangguran', 'bobot' => 5],
                    ['label' => 'Tidak Bersuami', 'bobot' => 3],

                ]
            ],
            [
                'kode' => 'C2',
                'nama_kriteria' => 'Pekerjaan Istri',
                'tipe' => TipeKriteria::Cost,

                'sub_kriteria' => [
                    ['label' => 'PNS', 'bobot' => 1],
                    ['label' => 'Wirausaha/Wiraswasta', 'bobot' => 2],
                    ['label' => 'Petani', 'bobot' => 3],
                    ['label' => 'Buruh', 'bobot' => 4],
                    ['label' => 'Pengangguran', 'bobot' => 5],
                    ['label' => 'Tidak Beristri', 'bobot' => 3],
                ]
            ],
            [
                'kode' => 'C3',
                'nama_kriteria' => 'Penghasilan Keseluruhan',
                'tipe' => TipeKriteria::Cost,
                'sub_kriteria' => [
                    ['label' => '>= 2.000.000', 'bobot' => 1],
                    ['label' => 'Rp. 1.600.000 – Rp. 2.000.000', 'bobot' => 2],
                    ['label' => 'Rp. 1.100.000 – 1.500.000', 'bobot' => 3],
                    ['label' => 'Rp. 500.000 – Rp. 1.000.000', 'bobot' => 4],
                    ['label' => '<=500.000', 'bobot' => 5],
                ]
            ],
            [
                'kode' => 'C4',
                'nama_kriteria' => 'Jumlah Tanggungan',
                'tipe' => TipeKriteria::Benefit,

                'sub_kriteria' => [
                    ['label' => '<= 2 Anak', 'bobot' => 1],
                    ['label' => '3 Anak', 'bobot' => 2],
                    ['label' => '4 Anak', 'bobot' => 3],
                    ['label' => '5 Anak', 'bobot' => 4],
                    ['label' => '>= 6 Anak', 'bobot' => 5],
                ]
            ],
            [
                'kode' => 'C5',
                'nama_kriteria' => 'Kondisi Rumah',
                'tipe' => TipeKriteria::Cost,
                'sub_kriteria' => [
                    ['label' => 'Betom', 'bobot' => 1],
                    ['label' => 'Batu Bara', 'bobot' => 2],
                    ['label' => 'Triplek', 'bobot' => 3],
                    ['label' => 'Papan', 'bobot' => 4],
                    ['label' => 'Bambu', 'bobot' => 5],
                    ['label' => 'Menumpang', 'bobot' => 2],
                ]
            ],
        ];
        //test


        $calonPenerima = [
            [
                'nik' => '3186234325644722',
                'nama' => 'alias',
                'alamat' => 'Alamat alias',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '20',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '5313213691544753',
                'nama' => 'nengsih',
                'alamat' => 'Alamat nengsih',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '12',
                    '3' => '13',
                    '4' => '22',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '5430360615473735',
                'nama' => 'Tambrin Bunais',
                'alamat' => 'Alamat Tambrin Bunais',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '2',
                    '2' => '12',
                    '3' => '13',
                    '4' => '21',
                    '5' => '24',
                ]
            ],
            [
                'nik' => '3456682534297804',
                'nama' => 'haeril',
                'alamat' => 'Alamat haeril',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '2',
                    '2' => '12',
                    '3' => '13',
                    '4' => '19',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '5045829047002727',
                'nama' => 'sarifuddin',
                'alamat' => 'Alamat sarifuddin',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '21',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '6294794731378785',
                'nama' => 'dedy wardono',
                'alamat' => 'Alamat dedy wardono',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '2505800389934993',
                'nama' => 'rahmat',
                'alamat' => 'Alamat rahmat',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '20',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '2569933687815032',
                'nama' => 'elkiyanto',
                'alamat' => 'Alamat elkiyanto',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '4',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '28',
                ]
            ],
            [
                'nik' => '6051832320929313',
                'nama' => 'baso baba',
                'alamat' => 'Alamat baso baba',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '2',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '0869242353807558',
                'nama' => 'nuraisyah',
                'alamat' => 'Alamat nuraisyah',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '12',
                    '3' => '15',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '9295460817644882',
                'nama' => 'markus',
                'alamat' => 'Alamat markus',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '21',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '6831451422302466',
                'nama' => 'yusuf r',
                'alamat' => 'Alamat yusuf r',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '20',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '9744861765889042',
                'nama' => 'a. manakku',
                'alamat' => 'Alamat a. manakku',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '2763020971377254',
                'nama' => 'anwar mh.saad',
                'alamat' => 'Alamat anwar mh.saad',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '2',
                    '2' => '12',
                    '3' => '13',
                    '4' => '19',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '2118414940548962',
                'nama' => 'syarifuddin',
                'alamat' => 'Alamat syarifuddin',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '2',
                    '2' => '12',
                    '3' => '13',
                    '4' => '21',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '7845803903980863',
                'nama' => 'muslimin',
                'alamat' => 'Alamat muslimin',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '2',
                    '2' => '12',
                    '3' => '13',
                    '4' => '20',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '3277271941977165',
                'nama' => 'ilham',
                'alamat' => 'Alamat ilham',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '22',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '5149186919079012',
                'nama' => 'hasmi',
                'alamat' => 'Alamat hasmi',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '12',
                    '3' => '13',
                    '4' => '21',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '3106970097974446',
                'nama' => 'umar',
                'alamat' => 'Alamat umar',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '1276141148648669',
                'nama' => 'sudrajat',
                'alamat' => 'Alamat sudrajat',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '12',
                    '3' => '13',
                    '4' => '22',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '1049311212917880',
                'nama' => 'baso edi',
                'alamat' => 'Alamat baso edi',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '2',
                    '2' => '12',
                    '3' => '13',
                    '4' => '21',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '8433882632129222',
                'nama' => 'ismail laho',
                'alamat' => 'Alamat ismail laho',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '2',
                    '2' => '12',
                    '3' => '13',
                    '4' => '22',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '5969389719306710',
                'nama' => 'nabila narti',
                'alamat' => 'Alamat nabila narti',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '12',
                    '3' => '13',
                    '4' => '19',
                    '5' => '24',
                ]
            ],
            [
                'nik' => '0645121570730339',
                'nama' => 'miftahul jannah',
                'alamat' => 'Alamat miftahul jannah',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '28',
                ]
            ],
            [
                'nik' => '7630997276754289',
                'nama' => 'Andy Prasetya',
                'alamat' => 'Alamat Andy Prasetya',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '2',
                    '2' => '12',
                    '3' => '13',
                    '4' => '19',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '4166706133502251',
                'nama' => 'Mattarima',
                'alamat' => 'Alamat Mattarima',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '21',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '9069339844343551',
                'nama' => 'Baharuddin',
                'alamat' => 'Alamat Baharuddin',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '19',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '1445127188240323',
                'nama' => ' Muhlis ',
                'alamat' => 'Alamat  Muhlis ',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '12',
                    '3' => '13',
                    '4' => '21',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '2789870592933993',
                'nama' => 'Harman Aziz',
                'alamat' => 'Alamat Harman Aziz',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '5091671923471744',
                'nama' => 'Nurdaiyah',
                'alamat' => 'Alamat Nurdaiyah',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '12',
                    '3' => '13',
                    '4' => '19',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '9802518825364972',
                'nama' => 'Mahrun',
                'alamat' => 'Alamat Mahrun',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '2635899129703467',
                'nama' => 'Mappiwali J',
                'alamat' => 'Alamat Mappiwali J',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '2',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '5196188153426644',
                'nama' => 'Syahrul Yadi',
                'alamat' => 'Alamat Syahrul Yadi',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '21',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '0765680003936632',
                'nama' => 'Ardiansyah',
                'alamat' => 'Alamat Ardiansyah',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '6297177961923951',
                'nama' => 'Dg Macinnong',
                'alamat' => 'Alamat Dg Macinnong',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '20',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '2700838055789280',
                'nama' => 'Manai',
                'alamat' => 'Alamat Manai',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '6120947397090108',
                'nama' => 'Baharudin',
                'alamat' => 'Alamat Baharudin',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '3715393425231656',
                'nama' => 'Beddu',
                'alamat' => 'Alamat Beddu',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '8048854061253376',
                'nama' => 'Jumardi',
                'alamat' => 'Alamat Jumardi',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '2788669461072180',
                'nama' => 'Jamal',
                'alamat' => 'Alamat Jamal',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '22',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '1730409905908554',
                'nama' => 'Samina',
                'alamat' => 'Alamat Samina',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '12',
                    '3' => '13',
                    '4' => '19',
                    '5' => '24',
                ]
            ],
            [
                'nik' => '4879637498962226',
                'nama' => 'Muh Zahir',
                'alamat' => 'Alamat Muh Zahir',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '2',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '5548799383509238',
                'nama' => 'Husni',
                'alamat' => 'Alamat Husni',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '12',
                    '3' => '13',
                    '4' => '19',
                    '5' => '24',
                ]
            ],
            [
                'nik' => '5758527976269197',
                'nama' => 'Imran',
                'alamat' => 'Alamat Imran',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '19',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '3624281231701980',
                'nama' => 'Mappa',
                'alamat' => 'Alamat Mappa',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '20',
                    '5' => '24',
                ]
            ],
            [
                'nik' => '1123636848756270',
                'nama' => 'Dg Mappile',
                'alamat' => 'Alamat Dg Mappile',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '7009599535224724',
                'nama' => 'Dg Mawellang',
                'alamat' => 'Alamat Dg Mawellang',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '19',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '9883365856146815',
                'nama' => 'Mappiasse',
                'alamat' => 'Alamat Mappiasse',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '20',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '0308077734765696',
                'nama' => 'Mustawi',
                'alamat' => 'Alamat Mustawi',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '19',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '3715787761281648',
                'nama' => 'Aswan',
                'alamat' => 'Alamat Aswan',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '3812285381814624',
                'nama' => 'Abd Hardi',
                'alamat' => 'Alamat Abd Hardi',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '19',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '3975298525531918',
                'nama' => 'Ambo Alle',
                'alamat' => 'Alamat Ambo Alle',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '12',
                    '3' => '13',
                    '4' => '21',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '3384314459883105',
                'nama' => 'Wahida',
                'alamat' => 'Alamat Wahida',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '2677676045338995',
                'nama' => 'Ifan Arif',
                'alamat' => 'Alamat Ifan Arif',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '21',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '9392364160641374',
                'nama' => 'Irwan',
                'alamat' => 'Alamat Irwan',
                'no_kk' => '',
                'desa' => '1',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '21',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '9718870002530500',
                'nama' => 'Fendi Lawanto',
                'alamat' => 'Alamat Fendi Lawanto',
                'no_kk' => '',
                'desa' => '2',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '21',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '6309346166914772',
                'nama' => 'Ahmad Albar',
                'alamat' => 'Alamat Ahmad Albar',
                'no_kk' => '',
                'desa' => '2',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '20',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '0427264800647287',
                'nama' => 'Rahmawati',
                'alamat' => 'Alamat Rahmawati',
                'no_kk' => '',
                'desa' => '2',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '9',
                    '3' => '15',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '2084106080661115',
                'nama' => 'Andi Ukkas',
                'alamat' => 'Alamat Andi Ukkas',
                'no_kk' => '',
                'desa' => '2',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '22',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '8692648261646086',
                'nama' => 'Irsan',
                'alamat' => 'Alamat Irsan',
                'no_kk' => '',
                'desa' => '2',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '20',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '6180261737595015',
                'nama' => 'Abd.Kadir',
                'alamat' => 'Alamat Abd.Kadir',
                'no_kk' => '',
                'desa' => '2',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '22',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '8972179256548600',
                'nama' => 'Miskin',
                'alamat' => 'Alamat Miskin',
                'no_kk' => '',
                'desa' => '2',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '22',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '1140039581117813',
                'nama' => 'Agus',
                'alamat' => 'Alamat Agus',
                'no_kk' => '',
                'desa' => '2',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '20',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '0299969877916175',
                'nama' => 'Rospandi',
                'alamat' => 'Alamat Rospandi',
                'no_kk' => '',
                'desa' => '2',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '1134655743048633',
                'nama' => 'Uke',
                'alamat' => 'Alamat Uke',
                'no_kk' => '',
                'desa' => '2',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '4',
                    '2' => '12',
                    '3' => '15',
                    '4' => '18',
                    '5' => '28',
                ]
            ],
            [
                'nik' => '6907646617368555',
                'nama' => 'Bahra',
                'alamat' => 'Alamat Bahra',
                'no_kk' => '',
                'desa' => '2',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '9',
                    '3' => '15',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '9995281158470939',
                'nama' => 'Kusnan Jaya Aris',
                'alamat' => 'Alamat Kusnan Jaya Aris',
                'no_kk' => '',
                'desa' => '2',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '1',
                    '2' => '12',
                    '3' => '13',
                    '4' => '20',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '7221603605227855',
                'nama' => 'Hardan',
                'alamat' => 'Alamat Hardan',
                'no_kk' => '',
                'desa' => '2',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '22',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '9073850115246982',
                'nama' => 'Diing',
                'alamat' => 'Alamat Diing',
                'no_kk' => '',
                'desa' => '2',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '22',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '8813471212855734',
                'nama' => 'Rosdianto',
                'alamat' => 'Alamat Rosdianto',
                'no_kk' => '',
                'desa' => '2',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '20',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '7657168280781327',
                'nama' => 'Marsudi',
                'alamat' => 'Alamat Marsudi',
                'no_kk' => '',
                'desa' => '2',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '19',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '2416032098321534',
                'nama' => 'Nurhaisyah',
                'alamat' => 'Alamat Nurhaisyah',
                'no_kk' => '',
                'desa' => '3',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '9',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '3845560775461347',
                'nama' => 'Robert',
                'alamat' => 'Alamat Robert',
                'no_kk' => '',
                'desa' => '3',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '21',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '8107867647090613',
                'nama' => 'Suparmin',
                'alamat' => 'Alamat Suparmin',
                'no_kk' => '',
                'desa' => '3',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '12',
                    '3' => '13',
                    '4' => '20',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '5467325838459594',
                'nama' => 'Ulfis Setiawan',
                'alamat' => 'Alamat Ulfis Setiawan',
                'no_kk' => '',
                'desa' => '3',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '2',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '6257084639795040',
                'nama' => 'Jikan',
                'alamat' => 'Alamat Jikan',
                'no_kk' => '',
                'desa' => '3',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '12',
                    '3' => '16',
                    '4' => '20',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '0626463346616895',
                'nama' => 'Warzito',
                'alamat' => 'Alamat Warzito',
                'no_kk' => '',
                'desa' => '3',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '20',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '3810173498448532',
                'nama' => 'Ngatemen',
                'alamat' => 'Alamat Ngatemen',
                'no_kk' => '',
                'desa' => '3',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '2',
                    '2' => '12',
                    '3' => '13',
                    '4' => '20',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '4585010222181402',
                'nama' => 'Dakok',
                'alamat' => 'Alamat Dakok',
                'no_kk' => '',
                'desa' => '3',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '7709461381312605',
                'nama' => 'Gito',
                'alamat' => 'Alamat Gito',
                'no_kk' => '',
                'desa' => '3',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '20',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '2497172663957593',
                'nama' => 'Maun',
                'alamat' => 'Alamat Maun',
                'no_kk' => '',
                'desa' => '3',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '20',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '9174568809177725',
                'nama' => 'Haerudin',
                'alamat' => 'Alamat Haerudin',
                'no_kk' => '',
                'desa' => '3',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '12',
                    '3' => '13',
                    '4' => '20',
                    '5' => '24',
                ]
            ],
            [
                'nik' => '3569035685281813',
                'nama' => 'Karsono',
                'alamat' => 'Alamat Karsono',
                'no_kk' => '',
                'desa' => '3',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '20',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '1584880936062609',
                'nama' => 'Rosmini',
                'alamat' => 'Alamat Rosmini',
                'no_kk' => '',
                'desa' => '3',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '12',
                    '3' => '16',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '7518315504934204',
                'nama' => 'EEM',
                'alamat' => 'Alamat EEM',
                'no_kk' => '',
                'desa' => '3',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '15',
                    '4' => '20',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '6930007946700118',
                'nama' => 'Masmud',
                'alamat' => 'Alamat Masmud',
                'no_kk' => '',
                'desa' => '3',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '12',
                    '3' => '16',
                    '4' => '18',
                    '5' => '24',
                ]
            ],
            [
                'nik' => '0823278289810001',
                'nama' => 'Muh saleh',
                'alamat' => 'Alamat Muh saleh',
                'no_kk' => '',
                'desa' => '3',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '7',
                    '3' => '13',
                    '4' => '20',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '5359056476774021',
                'nama' => 'Nur Akiba',
                'alamat' => 'Alamat Nur Akiba',
                'no_kk' => '',
                'desa' => '3',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '12',
                    '3' => '16',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '1366798674114706',
                'nama' => 'Komarun',
                'alamat' => 'Alamat Komarun',
                'no_kk' => '',
                'desa' => '3',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '20',
                    '5' => '24',
                ]
            ],
            [
                'nik' => '8173182188761548',
                'nama' => 'Manggi',
                'alamat' => 'Alamat Manggi',
                'no_kk' => '',
                'desa' => '3',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '24',
                ]
            ],
            [
                'nik' => '6330527684175815',
                'nama' => 'Hasbi',
                'alamat' => 'Alamat Hasbi',
                'no_kk' => '',
                'desa' => '3',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '21',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '0641865641536067',
                'nama' => 'Gio',
                'alamat' => 'Alamat Gio',
                'no_kk' => '',
                'desa' => '3',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '4331391682120760',
                'nama' => 'Arafah',
                'alamat' => 'Alamat Arafah',
                'no_kk' => '',
                'desa' => '3',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '20',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '5817319255278349',
                'nama' => 'Isbar',
                'alamat' => 'Alamat Isbar',
                'no_kk' => '',
                'desa' => '3',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '21',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '3805591789602986',
                'nama' => 'Ramadhan',
                'alamat' => 'Alamat Ramadhan',
                'no_kk' => '',
                'desa' => '3',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '12',
                    '3' => '13',
                    '4' => '19',
                    '5' => '24',
                ]
            ],
            [
                'nik' => '8381363252715805',
                'nama' => 'Hamzah',
                'alamat' => 'Alamat Hamzah',
                'no_kk' => '',
                'desa' => '3',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '22',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '4081583527200951',
                'nama' => 'Sarianto',
                'alamat' => 'Alamat Sarianto',
                'no_kk' => '',
                'desa' => '3',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '12',
                    '3' => '13',
                    '4' => '22',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '3332744748904416',
                'nama' => 'Nurhayati',
                'alamat' => 'Alamat Nurhayati',
                'no_kk' => '',
                'desa' => '3',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '12',
                    '3' => '16',
                    '4' => '18',
                    '5' => '28',
                ]
            ],
            [
                'nik' => '6760224754151327',
                'nama' => 'Elish',
                'alamat' => 'Alamat Elish',
                'no_kk' => '',
                'desa' => '3',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '12',
                    '3' => '13',
                    '4' => '21',
                    '5' => '24',
                ]
            ],
            [
                'nik' => '9750428772562158',
                'nama' => 'Kanude',
                'alamat' => 'Alamat Kanude',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '22',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '5094282221218868',
                'nama' => 'Amir',
                'alamat' => 'Alamat Amir',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '20',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '1815041384738213',
                'nama' => 'Asiman',
                'alamat' => 'Alamat Asiman',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '9',
                    '3' => '13',
                    '4' => '21',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '4296371587496015',
                'nama' => 'Lalu Sadri',
                'alamat' => 'Alamat Lalu Sadri',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '21',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '7645529357062333',
                'nama' => 'Iqsan',
                'alamat' => 'Alamat Iqsan',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '12',
                    '3' => '13',
                    '4' => '20',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '8390791879621365',
                'nama' => 'Darmanto',
                'alamat' => 'Alamat Darmanto',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '21',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '2678308290514912',
                'nama' => 'Mukmin',
                'alamat' => 'Alamat Mukmin',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '19',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '6383756075332086',
                'nama' => 'Ainal Candra',
                'alamat' => 'Alamat Ainal Candra',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '6640218227226713',
                'nama' => 'Alimuddin',
                'alamat' => 'Alamat Alimuddin',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '20',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '3578868754046920',
                'nama' => 'Suparman',
                'alamat' => 'Alamat Suparman',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '19',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '4464645174960979',
                'nama' => 'Robiana',
                'alamat' => 'Alamat Robiana',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '12',
                    '3' => '16',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '0078801167938346',
                'nama' => 'Rusdi',
                'alamat' => 'Alamat Rusdi',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '19',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '1729944947552011',
                'nama' => 'Jumadil',
                'alamat' => 'Alamat Jumadil',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '4139677125018571',
                'nama' => 'Teguh Darmawijaya',
                'alamat' => 'Alamat Teguh Darmawijaya',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '19',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '4167557566884530',
                'nama' => 'Sumiyati',
                'alamat' => 'Alamat Sumiyati',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '12',
                    '3' => '16',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '1826863336328566',
                'nama' => 'David',
                'alamat' => 'Alamat David',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '21',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '3884893709529957',
                'nama' => 'Rahmat A',
                'alamat' => 'Alamat Rahmat A',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '6553930947335767',
                'nama' => 'Mardan',
                'alamat' => 'Alamat Mardan',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '21',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '8500473663906627',
                'nama' => 'Ramadan',
                'alamat' => 'Alamat Ramadan',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '21',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '7099025447687879',
                'nama' => 'MuhThuhir Hasyri',
                'alamat' => 'Alamat MuhThuhir Hasyri',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '20',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '8692205599450174',
                'nama' => 'Muh Basri',
                'alamat' => 'Alamat Muh Basri',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '21',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '6101936873221954',
                'nama' => 'Johri',
                'alamat' => 'Alamat Johri',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '20',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '6773014461690548',
                'nama' => 'Lalu Jidah',
                'alamat' => 'Alamat Lalu Jidah',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '0972404148173670',
                'nama' => 'Baharudin',
                'alamat' => 'Alamat Baharudin',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '0548472228160032',
                'nama' => 'Gati',
                'alamat' => 'Alamat Gati',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '20',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '5725496700857100',
                'nama' => 'Lalu Saldi',
                'alamat' => 'Alamat Lalu Saldi',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '2',
                    '2' => '12',
                    '3' => '13',
                    '4' => '21',
                    '5' => '24',
                ]
            ],
            [
                'nik' => '5023269255954335',
                'nama' => 'Solihin',
                'alamat' => 'Alamat Solihin',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '21',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '2805733429648701',
                'nama' => 'Ayatullah',
                'alamat' => 'Alamat Ayatullah',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '28',
                ]
            ],
            [
                'nik' => '8702749267512749',
                'nama' => 'Suparman',
                'alamat' => 'Alamat Suparman',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '7657019119323341',
                'nama' => 'Mudah',
                'alamat' => 'Alamat Mudah',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '19',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '9938737733447417',
                'nama' => 'Renaldi',
                'alamat' => 'Alamat Renaldi',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '20',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '1974996675239377',
                'nama' => 'Saheruji',
                'alamat' => 'Alamat Saheruji',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '21',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '8760843176945738',
                'nama' => 'Nurpaiyah',
                'alamat' => 'Alamat Nurpaiyah',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '12',
                    '3' => '13',
                    '4' => '19',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '4908729373226714',
                'nama' => 'Lalu sukandi',
                'alamat' => 'Alamat Lalu sukandi',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '9197995917410291',
                'nama' => 'Maidan',
                'alamat' => 'Alamat Maidan',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '5883393759449874',
                'nama' => 'Nasgul',
                'alamat' => 'Alamat Nasgul',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '9418265030868790',
                'nama' => 'Rasta Tiro',
                'alamat' => 'Alamat Rasta Tiro',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '19',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '8054035765790403',
                'nama' => 'Dahri',
                'alamat' => 'Alamat Dahri',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '3',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
            [
                'nik' => '8311821728681763',
                'nama' => 'Suwarni',
                'alamat' => 'Alamat Suwarni',
                'no_kk' => '',
                'desa' => '4',
                'kecamatan' => 'Kecamatan Contoh',
                'kabupaten' => 'Kabupaten Contoh',
                'tanggal_input' => now(),
                'kriteria' => [
                    '1' => '5',
                    '2' => '12',
                    '3' => '13',
                    '4' => '18',
                    '5' => '26',
                ]
            ],
        ];



        foreach ($dataKriteria as $kriteria) {
            $kriteriaData = Kriteria::create([
                'kode' => $kriteria['kode'],
                'nama_kriteria' => $kriteria['nama_kriteria'],
                'tipe' => $kriteria['tipe'],
            ]);

            foreach ($kriteria['sub_kriteria'] as $sub) {
                SubKriteria::create([
                    'nama_sub_kriteria' => $sub['label'],
                    'bobot' => $sub['bobot'],
                    'kriteria_id' => $kriteriaData->id
                ]);
            }
        }

        foreach ($calonPenerima as $penerima) {
            $penerimaData = CalonPenerima::create([
                'nik' => $penerima['nik'],
                'nama' => $penerima['nama'],
                'alamat' => $penerima['alamat'],
                'no_kk' => $penerima['no_kk'],
                'desa' => $penerima['desa'],
                'kecamatan' => $penerima['kecamatan'],
                'kabupaten' => $penerima['kabupaten'],
                'tanggal_input' => $penerima['tanggal_input'],
            ]);

            foreach ($penerima['kriteria'] as $key => $value) {
                Penilaian::create([
                    'calon_penerima_id' => $penerimaData->id,
                    'kriteria_id' => $key,
                    'sub_kriteria_id' => SubKriteria::where('kriteria_id', $key)->inRandomOrder()->first()->id
                ]);
            }
        }
    }
}
